### ISSUE TITLE
Maven Build Error Issue

### ISSUE THREAD

**Issue by leesangboo** [digitalpetri/ua-server-sdk#3]
Fix Please.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project ua-server: Compilation failure: Compilation failure:
[ERROR] /C:/ua-server-sdk/ua-server/src/main/java/com/digitalpetri/opcua/sdk/server/OpcUaServer.java:[40,41] cannot access com.digitalpetri.opcua.stack.core.BuiltinReferenceType
[ERROR] bad class file: C:\Users\lsb\.m2\repository\com\digitalpetri\opcua\stack-core\1.0.0-SNAPSHOT\stack-core-1.0.0-SNAPSHOT.jar(com/digitalpetri/opcua/stack/core/BuiltinReferenceType.class)
[ERROR] bad signature: ¾

**Comment by kevinherron** [comment]
I've deployed new stack, client sdk, and server sdk artifacts. Try pulling everything and building again. If that doesn't work try clearing C:\Users\lsb.m2\repository\com\digitalpetri\opcua\

Hopefully once I've deployed some non-SNAPSHOT versions we won't see weird build issues like this any more.
